source:
  type: snowflake
  account: ${SNOWFLAKE_ACCOUNT_IDENTIFIER}
  user: ${SNOWFLAKE_USER}
  password: ${SNOWFLAKE_PASSWORD}
  role: melchi_db_admin
  warehouse: compute_wh
  database: melchi_cdc_db
  cdc_schema: melchi_cdc_db.streams
  cdc_strategy: cdc_streams
  batch_size: 10000
  replace_existing: true

target:
  type: duckdb
  database: ${DUCKDB_DATABASE_PATH}
  cdc_metadata_schema: melchi
  replace_existing: true

tables_config:
  path: "config/tables_to_transfer.csv"

logging:
  level: ${LOG_LEVEL}
  file: ${LOG_FILE_PATH}

# You can also include non-sensitive, hardcoded values
batch_size: 1000
retry_attempts: 3