# config/config.yaml

source:
  type: snowflake
  account: ${SNOWFLAKE_ACCOUNT_IDENTIFIER}
  user: ${SNOWFLAKE_USER}
  password: ${SNOWFLAKE_PASSWORD}
  role: melchi_db_admin
  warehouse: compute_wh
  change_tracking_database: melchi_cdc_db
  change_tracking_schema: streams

target:
  type: duckdb
  database: ${DUCKDB_DATABASE_PATH}
  change_tracking_schema: melchi

tables_config:
  path: "config/tables_to_transfer.csv"

logging:
  level: ${LOG_LEVEL}
  file: ${LOG_FILE_PATH}
